esphome:
  name: minimal-test

external_components:
  - source:
      type: local
      path: extras/ESPHome/components
    components: [dsc_keybus]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: "testnetwork"
  password: "testpassword"
  ap:
    ssid: "test-ap"

api:
  encryption:
    key: "Pl8wzUYOrdkKNtyeQVMsGz/cqYbl/cd6sZZkWa63f3s="

ota:
  - platform: esphome

logger:

dsc_keybus:
  access_code: "1234"

interval:
  - interval: 10s
    then:
      - lambda: |-
          ESP_LOGI("test", "millis: %lu", millis());