# DSC ESP32 Task Watchdog Timeout Fix - Standalone Mode Testing
# This configuration tests the ESP-IDF 5.3.2 task watchdog timeout fix
# using standalone mode to isolate the boot diagnostic from hardware issues

substitutions:
  accessCode: !secret access_code

esphome:
  name: dsc-esp32-boot-test

external_components:
  - source:
      type: local
      path: components
    components: [dsc_keybus]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    # Enhanced ESP-IDF configuration to prevent task watchdog timeout
    # These settings specifically address the ESP-IDF 5.3.2 "returned from app_main()" issue
    sdkconfig_options:
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "32768"
      CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0: y
      CONFIG_ESP_MAIN_TASK_PRIORITY: "1"
      CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "8192"
      CONFIG_ESP_SYSTEM_EVENT_TASK_PRIORITY: "20"
      CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH: "8192"
      CONFIG_FREERTOS_TIMER_TASK_PRIORITY: "22"
      CONFIG_FREERTOS_IDLE_TASK_STACKSIZE: "4096"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "300"             # 5 minutes timeout
      CONFIG_ESP_TASK_WDT_EN: y
      CONFIG_ESP_TASK_WDT_INIT: y
      CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0: y
      CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1: y
      CONFIG_ESP_TASK_WDT_PANIC: n                     # Reset instead of panic
      CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_ALL_CORES: y
      CONFIG_ESP_INT_WDT_EN: y
      CONFIG_ESP_INT_WDT_TIMEOUT_MS: "10000"
      CONFIG_ESP_INT_WDT_CHECK_CPU1: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_80: n
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: n
      CONFIG_ESP32_XTAL_FREQ_40: y
      CONFIG_ESP32_XTAL_FREQ_26: n
      CONFIG_PM_ENABLE: n
      CONFIG_ESP32_ENABLE_RTC_CLK_XTAL_32K: n
      CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE: "128"
      CONFIG_HEAP_POISONING_LIGHT: y
      CONFIG_HEAP_POISONING_COMPREHENSIVE: n
      CONFIG_HEAP_TRACING_STANDALONE: n
      CONFIG_HEAP_ABORT_WHEN_ALLOCATION_FAILS: n

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "DSC-ESP32-Boot-Test"
    password: !secret wifi_password

logger:
  baud_rate: 0
  level: VERBOSE

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# DSC KEYBUS CONFIGURATION IN STANDALONE MODE
# This bypasses hardware initialization to test pure boot stability
dsc_keybus:
  id: dsc_interface
  access_code: "$accessCode"
  series_type: "Classic"
  standalone_mode: true   # STANDALONE MODE - No hardware required
  debug: 1
  clock_pin: 18
  read_pin: 19     
  write_pin: 21
  pc16_pin: 17

# BOOT SUCCESS MONITORING  
interval:
  # ESP32 Boot Success Test - validates the task watchdog timeout fix
  - interval: 10s
    then:
      - lambda: |-
          static int boot_test_count = 0;
          boot_test_count++;
          
          ESP_LOGI("esp32_boot_test", "=== ESP32 BOOT SUCCESS TEST #%d ===", boot_test_count);
          ESP_LOGI("esp32_boot_test", "✅ SUCCESS: ESP32 successfully transitioned from app_main() to ESPHome main loop");
          ESP_LOGI("esp32_boot_test", "✅ Task watchdog timeout prevented by enhanced ESP-IDF configuration");
          ESP_LOGI("esp32_boot_test", "✅ ESP-IDF 5.3.2 + ESPHome 2025.7.5 compatibility verified");
          ESP_LOGI("esp32_boot_test", "Free heap: %zu bytes", esp_get_free_heap_size());
          ESP_LOGI("esp32_boot_test", "Test iteration: %d (running every 10 seconds)", boot_test_count);
          
          if (boot_test_count == 1) {
            ESP_LOGI("esp32_boot_test", "This test validates the fix for the ESP32 task watchdog timeout issue");
            ESP_LOGI("esp32_boot_test", "Issue: 'E (5923) task_wdt: Task watchdog got triggered. IDLE0 task not reset'");
            ESP_LOGI("esp32_boot_test", "Solution: Enhanced ESP-IDF stack sizes and watchdog configuration");
          }
          
          if (boot_test_count >= 18) { // 3 minutes of successful operation
            ESP_LOGI("esp32_boot_test", "🎉 COMPREHENSIVE TEST PASSED!");
            ESP_LOGI("esp32_boot_test", "ESP32 has been running stable for 3+ minutes without task watchdog timeout");
            ESP_LOGI("esp32_boot_test", "The ESP-IDF 5.3.2 configuration fixes are working correctly");
          }
          
          ESP_LOGI("esp32_boot_test", "==============================");

sensor:
  - platform: uptime
    name: "ESP32 Boot Test Uptime"
    id: uptime_seconds
    update_interval: 30s
    
  - platform: template
    name: "ESP32 Free Heap"
    id: free_heap_sensor
    update_interval: 30s
    unit_of_measurement: "bytes"
    lambda: |-
      return esp_get_free_heap_size();

text_sensor:
  - platform: version
    name: "ESP32 Boot Test Version"
  
  - platform: template
    name: "ESP32 Boot Test Status"
    id: boot_test_status
    update_interval: 30s
    lambda: |-
      float uptime = id(uptime_seconds).state;
      if (uptime < 30) {
        return {"Initializing - Testing boot stability"};
      } else if (uptime < 120) {
        return {"Running - Boot test in progress"};
      } else if (uptime < 180) {
        return {"Stable - Extended stability test"};
      } else {
        return {"SUCCESS - Task watchdog timeout fix verified"};
      }

button:
  - platform: restart
    name: "ESP32 Boot Test Restart"