esphome:
  name: test-dsc-esp32-arduino

external_components:
  - source:
      type: local
      path: components
    components: [dsc_keybus]

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: "test"
  password: "password"

api:

dsc_keybus:
  series_type: Classic
  access_code: "1234"
  debug: 0
