esphome:
  name: test-dsc-watchdog-esp32
  comment: "Test ESP32 watchdog timer improvements for DSC component"

external_components:
  - source:
      type: local
      path: components
    components: [dsc_keybus]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    # Use ESPHome default versions for maximum compatibility
    
    # ESP-IDF specific configurations to prevent boot hanging
    sdkconfig_options:
      # Main task stack size - increase to prevent stack overflow during init
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "16384"  # Default is 3584, increase to 16KB
      
      # System event task stack size
      CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "4096"  # Increase to 4KB
      
      # Timer task stack size  
      CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH: "4096"  # Increase to 4KB
      
      # WiFi task stack sizes for stability
      CONFIG_ESP32_WIFI_TASK_STACK_SIZE: "6144"  # Increase to 6KB
      CONFIG_ESP32_WIFI_RX_BUFFER_NUM: "16"     # Increase WiFi buffers
      CONFIG_ESP32_WIFI_TX_BUFFER_NUM: "16"
      
      # Memory management optimizations
      CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE: "64"  # Increase event queue
      CONFIG_FREERTOS_HZ: "1000"                # 1ms tick for responsive DSC processing
      
      # Watchdog timer configurations
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "30"       # 30 second timeout
      CONFIG_ESP_TASK_WDT_EN: y                 # Enable watchdog
      CONFIG_ESP_TASK_WDT_INIT: y               # Initialize early
      
      # Interrupt timing for DSC Keybus
      CONFIG_ESP_INT_WDT_TIMEOUT_MS: "2000"    # 2 second interrupt watchdog
      
      # Disable power management for consistent DSC timing
      CONFIG_PM_ENABLE: n

# Minimal required configuration for testing
logger:
  level: DEBUG

wifi:
  ssid: "test"
  password: "password"
  ap:
    ssid: "test-fallback"

api:

# Test DSC component with watchdog improvements
dsc_keybus:
  access_code: "1234"
  debug: 1

# Add a simple automation to test component functionality
binary_sensor:
  - platform: template
    name: "DSC Test Sensor"
    id: dsc_test