esphome:
  name: test-dsc-alarm-simple

external_components:
  - source:
      type: local
      path: components
    components: [dsc_keybus]

esp8266:
  board: nodemcuv2
  # PowerSeries only (no Classic support)

logger:

wifi:
  ssid: "test"
  password: "password"

api:

dsc_keybus:
  access_code: "1234"
  debug: 0