esphome:
  name: dscalarm-keypad

external_components:
  - source:
      type: local
      path: components
    components: [dsc_keybus]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ssid: "test"
  password: "password"

api:

dsc_keybus:
  series_type: Classic
  access_code: "1234"
  pc16_pin: 22
  debug: 0
