esphome:
  name: dsc-powerseries-test

esp8266:
  board: nodemcuv2

# Enable logging
logger:

dsc_keybus:
  series_type: PowerSeries
  access_code: "1234"
  debug: 1
  on_partition_status_change:
    then:
      - logger.log: "PowerSeries partition status changed"