# Home Assistant configuration.yaml example for DSC ESP32-POE Interface
# This configuration is fully compatible with the original HomeAssistant-MQTT examples

# MQTT Configuration
mqtt:
  broker: 192.168.1.100  # Replace with your ESP32-POE IP address
  client_id: homeAssistant
  username: ""           # Optional - configure in ESP32-POE web interface
  password: ""           # Optional - configure in ESP32-POE web interface

# Alarm Control Panel - Supports up to 8 partitions
alarm_control_panel:
  - platform: mqtt
    name: "Security Partition 1"
    state_topic: "dsc/Get/Partition1"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "1D"
    payload_arm_home: "1S"
    payload_arm_away: "1A"
    payload_arm_night: "1N"
  
  - platform: mqtt
    name: "Security Partition 2"
    state_topic: "dsc/Get/Partition2"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "2D"
    payload_arm_home: "2S"
    payload_arm_away: "2A"
    payload_arm_night: "2N"

# Partition Status Messages - Shows current system status
sensor:
  - platform: mqtt
    name: "Security Partition 1 Status"
    state_topic: "dsc/Get/Partition1/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"
  
  - platform: mqtt
    name: "Security Partition 2 Status"  
    state_topic: "dsc/Get/Partition2/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"

# Binary Sensors - Zone and System Status
binary_sensor:
  # System Trouble Indicator
  - platform: mqtt
    name: "Security Trouble"
    state_topic: "dsc/Get/Trouble"
    device_class: "problem"
    payload_on: "1"
    payload_off: "0"
  
  # Fire/Smoke Alarms (per partition)
  - platform: mqtt
    name: "Smoke Alarm 1"
    state_topic: "dsc/Get/Fire1"
    device_class: "smoke" 
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Smoke Alarm 2"
    state_topic: "dsc/Get/Fire2"
    device_class: "smoke"
    payload_on: "1" 
    payload_off: "0"
  
  # Zone Sensors - Configure up to 64 zones
  # These examples show the first 8 zones with different device classes
  - platform: mqtt
    name: "Front Door"
    state_topic: "dsc/Get/Zone1"
    device_class: "door"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Kitchen Window"
    state_topic: "dsc/Get/Zone2" 
    device_class: "window"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Living Room Motion"
    state_topic: "dsc/Get/Zone3"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Back Door"
    state_topic: "dsc/Get/Zone4"
    device_class: "door"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Bedroom Window" 
    state_topic: "dsc/Get/Zone5"
    device_class: "window"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Hallway Motion"
    state_topic: "dsc/Get/Zone6"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Basement Smoke"
    state_topic: "dsc/Get/Zone7" 
    device_class: "smoke"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Garage Door"
    state_topic: "dsc/Get/Zone8"
    device_class: "garage_door"
    payload_on: "1"
    payload_off: "0"
  
  # PGM Outputs - Programmable outputs from alarm panel
  - platform: mqtt
    name: "PGM Output 1"
    state_topic: "dsc/Get/PGM1"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "PGM Output 8"
    state_topic: "dsc/Get/PGM8" 
    payload_on: "1"
    payload_off: "0"

# Example Automations
automation:
  # Panic Button - Triggers alarm immediately
  - alias: "Security Panic Button"
    trigger:
      platform: state
      entity_id: input_boolean.panic_alarm  # Create this helper in UI
      to: 'on'
    action:
      service: mqtt.publish
      data:
        topic: "dsc/Set"
        payload: "P"
  
  # Auto-arm at night
  - alias: "Auto Arm Away at Night"
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.security_partition_1
      state: "disarmed"
    action:
      service: mqtt.publish
      data:
        topic: "dsc/Set"
        payload: "1A"

# Example Lovelace Card Configuration (add to dashboard YAML)
# type: alarm-panel
# entity: alarm_control_panel.security_partition_1
# name: Security System

# Example Button Card for Panic Alarm (add to dashboard)
# type: entity-button
# name: Panic Alarm
# tap_action:
#   action: call-service
#   service: mqtt.publish
#   service_data:
#     payload: P
#     topic: dsc/Set
# hold_action:
#   action: none
# show_icon: true
# show_name: true
# entity: alarm_control_panel.security_partition_1

# Notes:
# 1. Replace zone names with your actual zone descriptions
# 2. Add/remove zones as needed (up to 64 zones supported)
# 3. Configure device_class appropriately for each zone type
# 4. The ESP32-POE web interface allows customization of zone names and classes
# 5. All topics are configurable via the ESP32-POE web interface
# 6. MQTT credentials can be configured in the ESP32-POE web interface